### ISSUE TITLE
[USER] Sign UP\IN\OUT

### ISSUE THREAD

**Issue by BorodaUA** [ITA-Dnipro/Dp-Retraining-Python#2]
AS A person
I WANT TO sign up to website
SO THAT I can view, and edit information that belongs to me, and act on my behalf.
===
### Links to tasks
- [X] [Create '/users' endpoints](https://github.com/ITA-Dnipro/Dp-Retraining-Python/issues/4)
- [X] [Create '/auth' endpoints](https://github.com/ITA-Dnipro/Dp-Retraining-Python/issues/3)
- [x] [Create sign up email confirmation](https://github.com/ITA-Dnipro/Dp-Retraining-Python/issues/38)
