### ISSUE TITLE
[FUNDRAISE] Create '/fundraisers' endpoints.

### ISSUE THREAD

**Issue by BorodaUA** [ITA-Dnipro/Dp-Retraining-Python#86]
### TODO:
- [x] Create Fundraise table
- [x] Create routes:
```
GET /fundraisers/
POST /fundraisers/
GET /fundraisers/{id}
PUT /fundraisers/{id}
DELETE /fundraisers/{id}
```
- [x] Create DBService>Service>Endpoint logic for '/fundraisers/{id}/statuses' endpoints.
- [x] Create DB CRUD logic
- [x] Create Services logic
- [x] Create FundraiseStatus table
- [x] Refactor all /charities endpoints.
- [x] Create tests
